# docker-compose.yml
version: "3.8"

services:
  postgres:
    image: pgvector/pgvector:pg16
    container_name: postgres_db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped

  app:
    build: .
    container_name: qufy_app_2
    ports:
      - "8501:8501"
    volumes:
      - .:/app
    depends_on:
      - postgres
    env_file:
      - .env
    environment:
      - OLLAMA_HOST=host.docker.internal
    restart: unless-stopped

volumes:
  postgres_data:
